package com.bookstore.model;

public class User {
    private int id;
    private String name;
    private String username;
    private String password;
    private String email;
    private String role; // "USER" or "ADMIN"
    private String address;

    // 1. Default Constructor
    public User() {}

    // 2. Constructor for Registration (ID is auto-generated by DB, so we don't need it here)
    public User(String name, String username, String password, String email, String address) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.email = email;
        this.role = "USER";   // Default role
        this.address = address;
    }

    // 3. Getters and Setters
    public int getId() { return id; }
    public void setId(int id) { this.id = id; }

    public String getName() { return name; }
    public void setName(String name) { this.name = name; }

    public String getUsername() { return username; }
    public void setUsername(String username) { this.username = username; }

    public String getPassword() { return password; }
    public void setPassword(String password) { this.password = password; }

    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }

    public String getRole() { return role; }
    public void setRole(String role) { this.role = role; }

    public String getAddress() {return address;}
    public void setAddress(String address) {this.address = address;}
}
